# Generated by Django 5.2.7 on 2025-10-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('idade', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Em tratamento', 'Em tratamento'), ('Adotado', 'Adotado')], default='Disponível', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_animais/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
