# Generated by Django 5.2.7 on 2025-11-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petguard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_tratamento', 'Em tratamento'), ('adotado', 'Adotado')], default='disponivel', max_length=30),
        ),
    ]
