# Generated by Django 5.2.7 on 2025-11-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petguard', '0002_alter_animal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='animais/'),
        ),
    ]
